% Default figure properties
set(0, 'DefaultFigureColor', 'w', ...
'DefaultFigurePaperType', 'a4letter', ...
'DefaultAxesColor', 'none', ...
'DefaultAxesDrawmode', 'fast', ...
'DefaultAxesFontUnits', 'points',...
'DefaultAxesFontSize', 16, ...
'DefaultAxesFontAngle', 'Normal', ...
'DefaultAxesFontName', 'Helvetica', ...
'DefaultAxesFontWeight', 'Bold', ...
'DefaultAxesGridLineStyle', ':', ...
'DefaultAxesInterruptible', 'on', ...
'DefaultAxesLayer', 'Bottom', ...
'DefaultAxesNextPlot', 'replace',...
'DefaultAxesUnits', 'normalized', ...
'DefaultAxesXcolor', 0.2*ones(1,3), ...
'DefaultAxesYcolor', 0.2*ones(1,3), ...
'DefaultAxesZcolor', 0.2*ones(1,3), ...
'DefaultAxesVisible', 'on', ...
'DefaultLineColor', 'k', ...
'DefaultLineLineStyle', '-', ...
'DefaultLineLineWidth', 1.75, ...
'DefaultLineMarker', 'none', ...
'DefaultLineMarkerSize', 10, ...
'DefaultTextColor', 0.2*ones(1,3), ...
'DefaultTextFontUnits', 'Points',...
'DefaultTextFontSize', 16, ...
'DefaultTextFontName', 'Helvetica', ...
'DefaultTextVerticalAlignment', 'middle', ...
'DefaultAxesColorOrder',cbrewer('qual','Set1',8), ...
'DefaultTextHorizontalAlignment', 'left');
