%% better plotting function
%  Niru Maheswaranathan
%  3 Feb 2012

function makepretty(varargin)

    %set(gca,'TickDir','out','Box','off');
    grid on;
    set(gca, ...
    'Box'         , 'off'     , ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.01 .01] , ...
    'XMinorTick'  , 'off'      , ...
    'YMinorTick'  , 'off'      , ...
    'YGrid'       , 'off'      , ...
    'XGrid'       , 'off'      , ...
    'XColor'      , 0.3*ones(1,3), ...
    'YColor'      , 0.3*ones(1,3), ...
    'LineWidth'   , 1         );
    %'YMinorGrid'  , 'on'      , ...
    %'XMinorGrid'  , 'on'      , ...
